  <footer class="footer">
    <div id="contact">
      <h2>Contact us</h2>
      <a href="mailto:info@unlimitedmoneyltd.com.au">info@unlimitedmoneyltd.com.au</a>
    </div>
    <div id="contact">
            <a href="https://github.com/106215431/COS10026-Project-Part-2" target="_blank">GitHub</a>
        </div>
    <div id="Jira">
      <a href="https://seadog.atlassian.net/jira/software/projects/W0WTP/boards/4/backlog">https://seadog.atlassian.net/jira/software/projects/W0WTP/boards/4/backlog</a>
    </div>
  </footer>
  </body>
<!-- 
  Portions of this HTML code were generated with assistance from 
  ChatGPT (GPT-5) and/or GitHub Copilot.
  Reviewed, modified, and approved by Pham Bao Lam, Vu Gia Hien, Ngo Nhat Nam, Nguyen Minh Hieu.
-->
</html>