    <header>
        <nav class="navbar">
            <div class="logo"><a href="index.php">💰 Unlimited Money Ltd</a></div>
            <a href='http://localhost/COS10026-Project-Part-2/project2/index.php'> Back to Website </a>
            <a href='http://localhost/COS10026-Project-Part-2/project2/manager_logout.php'> Log out </a>
            <a href="#contact">Contact</a>
        </nav>
        <hr/>
    </header>