    <header>
        <nav class="navbar">
            <div class="logo"><a href="index.php">💰 Unlimited Money Ltd</a></div>
            <a href="jobs.php">Job Listings</a>
            <a href="apply.php">Job Applications</a>
            <a href="about.php">About Us</a>
            <a href="manager_login.php">Log in (ADMIN Only)</a>
            <a href="#contact">Contact</a>
        </nav>
        <hr/>
    </header>